### PR TITLE
Add a note in the Readme file

### PR DESCRIPTION
**Pull request by NewIncome**
Initialized a repo to be ready to work with React on a Calculator project:
- initialized a React app with create-react-app
- added 2 additional packages to work with directly:
  1. prop-type
  2. big.js
- deployed to Heroku with the help of the mars buildpack
- added and setup linter

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @NewIncome 
### You have done really well so far :clap: However, you have a few issues to fix:-
- [ ] Kindly fix the issues linting issues in the pull request, install all the required dependencies, configure them properly, and run commands `npx eslint .` and `npx stylelint "**/*.{css,scss}"` respectively. [Follow this guide](https://github.com/microverseinc/linters-config/tree/master/react-redux)
- [ ] You did not have to delete all the files, you should leave files like app.js, index.js
### Make the changes and submit for another code review. Good luck.
- Happy coding!

**Comment by NewIncome** [comment]
> Hello @NewIncome
> ### You have done really well so far clap However, you have a few issues to fix:-
> 
>     * [ ]  Kindly fix the issues linting issues in the pull request, install all the required dependencies, configure them properly, and run commands `npx eslint .` and `npx stylelint "**/*.{css,scss}"` respectively. [Follow this guide](https://github.com/microverseinc/linters-config/tree/master/react-redux)
> 
>     * [ ]  You did not have to delete all the files, you should leave files like app.js, index.js
> 
> 
> ### Make the changes and submit for another code review. Good luck.
> 
>     * Happy coding!


Hi @rOluochKe 
Quick question, don't know if I missed it but is there a place to check which files are the basic ones we should usually leave to start an empty project?
That would awesome, thanks!!

**Comment by rOluochKe** [comment]
> > Hello @NewIncome
> > ### You have done really well so far clap However, you have a few issues to fix:-
> > ```
> > * [ ]  Kindly fix the issues linting issues in the pull request, install all the required dependencies, configure them properly, and run commands `npx eslint .` and `npx stylelint "**/*.{css,scss}"` respectively. [Follow this guide](https://github.com/microverseinc/linters-config/tree/master/react-redux)
> > 
> > * [ ]  You did not have to delete all the files, you should leave files like app.js, index.js
> > ```
> > 
> > 
> > ### Make the changes and submit for another code review. Good luck.
> > ```
> > * Happy coding!
> > ```
> 
> Hi @rOluochKe
> Quick question, don't know if I missed it but is there a place to check which files are the basic ones we should usually leave to start an empty project?
> That would awesome, thanks!!
## You can always start with the 2 files  I mentioned and maybe with a title

**Review by rOluochKe — APPROVED** [review]
### You got it right. The project has been approved. Congratulations :boom: :100:
### Merge the milestone and submit it. good luck with the next one.
- Happy coding!

**Pull request merged**
