### PR TITLE
Feature/milestone 5

### PR DESCRIPTION
**Pull request by NewIncome**
Correctly implement the complete logic and the clickHandlers and the Display functionality

### CODE REVIEW

**Review by lucasmazo23 — CHANGES_REQUESTED** [review]
## Changes required 🔧
### You are doing a great job so far, and the project is looking good.
 
### For the project to get approved kindly implement these changes:
 
### Required changes:
- [x] [REQUIRED] I'm having troubles using the division in the calculator
calc

- [ ] [OPTIONAL] I saw some uses of the `function` keyword, where you could be using an arrow function.

### Happy coding! 💻
## Lucas Mazo

**Review by Forison — CHANGES_REQUESTED** [review]
## Status::changes required⛔️
#### The issue raised in the previous review still persist, kindly address it submit a re-review🤗 .
* [x] performing computation which involves a division does not function as required ie
`number1` `/` `number2` does not work.
* [x] The `+/-` should mutate both `number1` and `number2` when selected at the time `number1` and `number2` have been inputted. ie when `1+2` is inputted then `+/-` is followed then our input should be modified to `-1-2`.
> don't forget to properly address the division of a number by zero.
#### That is it kindly make the change and submit a re-review👨‍🔧.
#### Happy coding👨‍💻.
Addo Forison

**Comment by NewIncome** [comment]
jejeje, sorry, forgot about that
And thanks for the sign reminder, didn't exactly know what was expected, with the example totally understood it
Thanks @Forison!

**Review by shloch — APPROVED** [review]
## Hello @NewIncome , 

Great job addressing the issues raised by the former reviewer. I noticed the change and this is great.
calc

This is ready for merging and you can move to future challenge. Thumbs up

**Pull request merged**
